nodes:
  - url: "https://api.openai.com/v1/models"
    max_bpm: 1000000
    max_rpm: 100
  - url: "https://api.openai.com/v1/models"
    max_bpm: 1500000
    max_rpm: 150
  - url: "https://api.openai.com/v1/models"
    max_bpm: 2000000
    max_rpm: 200
port: "8080"