nodes:
  - url: "http://mock-server-1"
    max_bpm: 3000
    max_rpm: 100
  - url: "http://mock-server-2"
    max_bpm: 5000
    max_rpm: 150
  - url: "http://mock-server-3"
    max_bpm: 2000000
    max_rpm: 200
port: "8080"
